name: update-daily

on:
  workflow_dispatch:
  schedule:
    # 含义：在周一到周五(1-5)，UTC时间 13:00 到 21:00 之间，每小时的 10分 和 40分 运行
    # 这样可以覆盖美股 09:40 到 16:40 (甚至更晚一点) 的所有时段
    - cron: "10,40 13-21 * * 1-5"

jobs:
  build:
    if: github.repository == 'pokedo0/index-constituents'

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: pip-install
      run: pip install -r requirements.txt
    - name: update-data
      run: ./update-daily.sh
    - name: update-timestamp
      run: ./update-timestamp.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
